name: PHPUnit

on: [ push, pull_request ]

jobs:
  ci:
    name: Test PHP ${{ matrix.php-version }} on swoole(${{ matrix.swoole-version }})
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php-version: ['8.0']
        swoole-version: [ 'v4.5.11', 'v4.6.7', 'v4.7.1', 'v4.8.6', 'master' ]
      max-parallel: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: phpize
          ini-values: opcache.enable_cli=1
          coverage: none
      - name: Setup Swoole
        run: |
          cd /tmp
          sudo apt-get install libcurl4-openssl-dev
          wget https://github.com/swoole/swoole-src/archive/${{ matrix.swoole-version }}.tar.gz -O swoole.tar.gz
          mkdir -p swoole
          tar -xf swoole.tar.gz -C swoole --strip-components=1
          rm swoole.tar.gz
          cd swoole
          phpize
          ./configure --enable-openssl --enable-http2 --enable-swoole-curl --enable-swoole-json
          make -j$(nproc)
          sudo make install
          sudo sh -c "echo extension=swoole > /etc/php/${{ matrix.php-version }}/cli/conf.d/swoole.ini"
          php --ri swoole
      - name: Setup Packages
        run: composer update -o --no-scripts
      - name: Run Test Cases
        run: |
          vendor/bin/php-cs-fixer fix --dry-run
          composer test -- --exclude-group NonCoroutine
          vendor/bin/phpunit --group NonCoroutine
